dubbo:
  application:
    qos-enable: false

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.30.160.250:8848
        register-enabled: false
  devtools:
    restart:
      enabled: true
  datasource:
    #   公网: 117.79.92.68  192.168.1.205
    url: jdbc:mysql://192.168.1.205:3306/lenos?useUnicode=true&useSSL=false&characterEncoding=UTF-8
    username: lenosWriterH
    password: U0qM5LRiCBLm
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    encoding:
      force: true
  boot:
    admin:
      client:
        url: http://localhost:8082


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  redis:
    host: 127.0.0.1
    port: 6379



mybatis:
  type-aliases-package: com.len.entity
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true

mapper:
  mappers:
    - com.len.base.BaseMapper
    - tk.mybatis.mapper.common.Mapper
  not-empty: true
  identity: mysql


# PageHelperConfig 可以替代此方案
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

lenosp:
  uploadPath: ./file/
  isDayType: false

  imagePath: ./image/

logging:
  file: ./logs/lenosp-log.log
  level:
    root: warn
    com.len.mapper: debug

dataType: mysql

redis:
  prefix: len_